MainCode/force-app/main/default/objects/Utterance_Log__c/Utterance_Log__c.object-meta.xml
<CustomObject>
    <label>Utterance Log</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utterance Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MainCode/force-app/main/default/objects/Utterance_Log__c/fields/Chat_Transcript__c.field-meta.xml
<CustomField>
    <fullName>Chat_Transcript__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chat Transcript</label>
    <referenceTo>LiveChatTranscript</referenceTo>
    <relationshipLabel>Utterance Logs</relationshipLabel>
    <relationshipName>Utterance_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

MainCode/force-app/main/default/objects/Utterance_Log__c/fields/CurrentUtterance__c.field-meta.xml
<CustomField>
    <fullName>CurrentUtterance__c</fullName>
    <label>CurrentUtterance</label>
    <type>TextArea</type>
</CustomField>

MainCode/force-app/main/default/classes/CookbookBot_LogUtterance.cls
public with sharing class CookbookBot_LogUtterance 
{
    public class LogInput{
      @InvocableVariable(required=false)
       public String sCurrentUtterance;
       @InvocableVariable(required=false)
       public String sLiveAgentTranscriptId;
   }
         @InvocableMethod(label='Log Utterance')
         public static void logUtterance(List<LogInput> inputParameters)
   { 
         String sCurrentUtterance = inputParameters[0].sCurrentUtterance;
         String sLiveAgentTranscriptId = inputParameters[0].sLiveAgentTranscriptId;

 
      //Create a new Utterance Log record
       Utterance_Log__c logRecord = new Utterance_Log__c();
 
       // Store the utterance
       
       logRecord.CurrentUtterance__c = sCurrentUtterance;
       logRecord.Chat_Transcript__c = sLiveAgentTranscriptId;
       
       // Save the log utterance record to our org
       insert logRecord;
       system.debug('success');
   }
    
}