MainCode/force-app/main/default/objects/Broker__c/Broker__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MainCode/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property1</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MainCode/force-app/main/default/objects/Property__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <referenceTo>Broker__c</referenceTo>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

MainCode/force-app/main/default/classes/PropertyUtility.cls
public class PropertyUtility {
    public static void newListedProperties()
    {
        List<Property__c> newPropList = new List <Property__c>	([select Name,Broker__r.Email__c,Days_On_Market__c from Property__C
                                                                  Where Days_On_Market__c <= 30]); 
        for(property__c p :newPropList)
        {
            string propEmail = p.Name +':'+ p.Broker__r.Email__c;
            system.debug(propEmail);
        }
    }
}